create table topic
(
    id     bigint generated by default as identity,
    header varchar(255),
    title  varchar(255),
    primary key (id)
);

create table comment
(
    id     bigint generated by default as identity,
    text varchar(255),
    topic_id  bigint,
    primary key (id)
);

alter table if exists comment
    add constraint fk_comment_topic
    foreign key (topic_id)
    references topic;