create table topic
(
    id     bigint generated by default as identity,
    header varchar(255),
    title  varchar(255),
    primary key (id)
);

create table comment
(
    id     bigint generated by default as identity,
    text varchar(255),
    topic_id  bigint,
    primary key (id)
);

    create table test_validation (
        id bigint generated by default as identity,
        age integer not null check (age>=18),
        country varchar(255),
        email varchar(320),
        full_name varchar(250),
        phone_number varchar(255),
        primary key (id)
    );

alter table if exists comment
    add constraint fk_comment_topic
    foreign key (topic_id)
    references topic;